version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:80"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
